### ISSUE TITLE
An example of letting the user authenticate would be welcome!

### ISSUE THREAD

**Issue by Yoric** [dsferruzza/actix-web-middleware-keycloak-auth#1]
Thanks for this crate, this seems to be exactly what I'm looking for!

Now, I'll be even happier if I can find an example with the full flow:

1. user connects to `http://example.com/private`;
2. user is sent to the SSO server;
3. once connected, user continues on `http://example.com/private`.

**Comment by dsferruzza** [comment]
Hi!

For now the whole OIDC Standard Flow is out of scope here.
The point of this middleware is to verify JWT that were obtained beforehand (no matter how), as one would do in a REST API.

In my current stack, Actix Web apps act as microservices (API only): each API call must provide a JWT that was issued before (from Keycloak, using another app as client) and I have frontend apps (Vue.js) that handle the OIDC Standard Flow when user must login.

I guess it might make sense to have my middleware handle both, but I don't need it right now and it is too far from my use cases to justify spending too much of my time and having no real world project to test it 😬

That being said, implementing the Standard Flow directly in your Actix Web app seems manageable. You could leverage the [openidconnect crate](https://crates.io/crates/openidconnect) or implement only a subset of what you need by yourself using [reqwest](https://crates.io/crates/reqwest) and (maybe) [jsonwebtoken](https://crates.io/crates/jsonwebtoken).

Do this makes sense to you?
(If you want to discuss it further in French, feel free to email me!)
