### ISSUE TITLE
impl PassthroughPolicy for Fn

### ISSUE THREAD

**Issue by Ploppz** [dsferruzza/actix-web-middleware-keycloak-auth#7]
I was going to add something like this in a PR

```rust
impl<F> PassthroughPolicy for F
    where F: Fn(&AuthError) -> PassthroughAction + Clone
{
    fn policy(&self, error: &AuthError) -> PassthroughAction {
        self(error)
    }
}
```

but couldn't (immediately)  figure out some compiler errors I got when trying to use my changes in an existing project. I previous used `v0.4.0-beta.2`, worked from that commit, and now got error:
```
error[E0599]: no variant or associated item named `from_message` found for enum `AnyBody` in the current scope
   --> /home/erlend/.cargo/git/checkouts/actix-web-prom-af77977b77662c26/fc05d50/src/lib.rs:519:22
    |
519 |             AnyBody::from_message(StreamLog {
    |                      ^^^^^^^^^^^^ variant or associated item not found in `AnyBody<_>`

```

**Comment by dsferruzza** [comment]
There might be an actual issue somewhere, but why no just do your implementation in its own struct instead of going generic over `Fn(&AuthError) -> PassthroughAction + Clone`? I mean something like this: https://github.com/dsferruzza/actix-web-middleware-keycloak-auth/blob/master/src/lib.rs#L327-L335

_Also, out of curiosity, what is your use case that would need to define a custom policy?_

**Comment by Ploppz** [comment]
Because it's much easier to just pass a closure without having to create a struct. Why should we not do this generic impl?

The use case is that I want to log the auth errors.

**Comment by dsferruzza** [comment]
I added this implementation on a branch (see #8) and tested it on an example: it seems to work. I could not reproduce the error you got.

Does this impl works for you?

**Comment by Ploppz** [comment]
Sorry for the delay. I tried to test it. First issue is that `futures_util 0.3.18` has been yanked.
But it doesn't matter much because I get compiler errors from crates like `actix_cors` and `actix-web-middleware-keycloak-auth`. They are all very finicky and it becomes a problem as soon as some beta version numbers are changed in Cargo.lock. Couldn't figure out this dependency puzzle. I hope that actix-web 4.0.0 is released soon...
I'll update this issue once that happens

**Comment by dsferruzza** [comment]
Thanks for the head up on `futures_util 0.3.18` beeing yanked!
I updated `master` and rebased the `closure-policy` branch.

You can pull and retry, it should work now!

**Comment by Ploppz** [comment]
For the record, waiting for this before I can try it out in my application: https://github.com/nlopes/actix-web-prom/issues/60. However, yes can I confirm by looking at your code that that is what I desired and if you merge that PR we can close this issue.

**Comment by Ploppz** [comment]
I just successfully used your branch in my application.

**Comment by dsferruzza** [comment]
Wonderful! I merged the branch 🙂
